name: guest_book
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  flutterfire_ui: ^0.4.3+20
  timeago: ^3.3.0
  intl: ^0.17.0
  animated_widgets: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets: 
    - assets/images/